server:
  port: ${service.port:8090}
  contextPath: ${contextPath:/}

eureka:
  instance:
    nonSecurePort: 8090
    statusPageUrlPath: ${server.contextPath}/info
    healthCheckUrlPath: ${server.contextPath}/health
    appname: ${spring.application.name}
    instanceId: ${spring.application.name}:${APP_VERSION}:${spring.application.instance_id:${HOSTNAME}}
    metadataMap:
      instanceId: ${spring.application.name}_v${APP_VERSION}:${spring.application.instance_id:${HOSTNAME}}
      version: ${APP_VERSION}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/

# H2
spring.h2.console.enabled: true
spring.h2.console.path: /h2
# Datasource
spring:
  datasource:
    url: jdbc:h2:mem:example-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
